version: '3.9'

services:
  user_db:
    image: postgres:latest
    ports:
      - 5431:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/user_db/data
    environment:
      - POSTGRES_PASSWORD=user_service
      - POSTGRES_USER=user_service
      - POSTGRES_DB=user_db
